[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraLight"

[scrolling]
history = 0

[terminal]
shell.program = "/bin/zsh"
shell.args = ["-l", "-c", "tmux attach-session || tmux"]

[window]
decorations = "Buttonless"
opacity = 1
blur = true
startup_mode = "Maximized"
option_as_alt = "Both"
